config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :carts
  resources :line_items do
    member do
      put 'decrement'
    end
  end
  resources :store

  get 'admin/index'
  resources :articles do
    member do
      get 'copy'
      post 'save_copy'
    end
  end
  resources :models
  resources :brands
  resources :categories
  resources :colors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "admin#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :model
  belongs_to :color
  has_one :brand, through: :model

  validates :num , presence: true, numericality: { in:15..45}
  validates :stock, presence: true, numericality: {in: 0..99 }
  validates :price, presence: true
  validates :model_id , inclusion:  Model.pluck(:id) 
  validates :color_id , inclusion: Color.pluck(:id)

  def get_code
    model = Model.find(model_id)
    brand = Brand.find(model.brand_id)
    color = Color.find(color_id)
    cod = brand.cod + model.cod + color.cod + num.to_s
  end

  def exists?(num, color)
    article = Article.where(num: num, color: color, model: model.id)
    !article.empty?
  end
  
  scope :ordered, -> { includes(:brand).order('brands.cod ASC').includes(:model).order('models.cod ASC').includes(:color).order('colors.cod ASC').order(:num) }

  scope :active, -> { where('stock > ?', 0) }


  scope :group_by_colors, -> {group(:color_id)}

end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :models,  :dependent => :restrict_with_error

    validates :cod , presence: true , uniqueness: true, length: { is: 2}, format: {with: /[A-Z]/}
    validates :name , presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}


end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :delete_all
    #belongs_to :cart, optional: true
    belongs_to :user

    def add_article(article)
        current_article = line_items.find_by(article_id: article.id)
        if current_article
            if article.stock > current_article.quantity
                current_article.quantity +=1
            else
                return false
            end

        else
            current_article = line_items.build(article_id: article.id)
            current_article.quantity = 1
        end
        current_article
    end

    def totals
        data = {
            :sum => 0,
            :total_items => 0
        }
        sum = 0
        line_items.each do |line_item|
            data[:sum] += line_item.total_price
            data[:total_items] += line_item.quantity
        end
        data
    end

    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :models, :dependent => :restrict_with_error


    validates :cod , presence: true , uniqueness: true, numericality: { only_integer: true }, length: { is: 2}
    validates :name , presence: true , uniqueness: true , length: { minimum: 3, maximum: 10}
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :articles, :dependent => :restrict_with_error
    #before_destroy :check_articles
    validates :cod , presence: true , uniqueness: true, numericality: { only_integer: true }, length: { is: 2}
    validates :name , presence: true, uniqueness: true, length: {minimum: 1, maximum: 10}

    def check_articles
        if !articles.empty?
            errors.add_to_base("Cannot delete color #{name} ")
            return false
        end
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :article
  belongs_to :cart, optional: true
  belongs_to :order, optional: true


  def total_price
    article.price * quantity
  end

end

app/models/model.rb
class Model < ApplicationRecord

  class ModelValidator < ActiveModel::Validator
    def validate(record)
      found = Model.find_by(cod: record.cod, brand: record.brand)
      if (found && found.id!=record.id)
        record.errors.add :base, "The model '#{record.cod}' for brand '#{record.brand.cod}' exists"
      end
    end
  end

  belongs_to :brand
  belongs_to :category
  has_many :articles, :dependent => :restrict_with_error

  validates :name , presence: true
  validates :cod , presence: true , numericality: { only_integer: true }, length: { is: 3}
  validates :brand_id , inclusion:  Brand.pluck(:id) 
  validates :category_id, inclusion: Category.pluck(:id)
  validates_with ModelValidator


  def get_brands
    @brands = Brand.all
  end

  def brand_with_model
    "#{brand.name} - #{name}"
  end

  scope :ordered, -> { includes(:brand).order('brands.cod ASC').order(:cod) }

  scope :with_articles, -> {joins(:articles).where('stock > ?', 0).group(:model_id)}


end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items

    validates :name , presence: true


    def add_articles_in_cart(cart)
        cart.line_items.each do |line_item|
            line_item.cart_id = nil
            article = line_item.article
            article.transaction do
                article.stock -= line_item.quantity
                article.save
            end
            line_items << line_item
        end
    end

    def check_availability(cart)
        errors = []
        cart.line_items.each do |line_item|
            if line_item.quantity > line_item.article.stock
                errors.push(line_item.article)
            end
        end
        errors
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts/1 or /carts/1.json
  def show
  end


  def destroy
    respond_to do |format|
      if  @cart.destroy
        format.html { redirect_to store_index_path, notice: "Cart was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      #@cart = Cart.find(params[:id])
      @cart = Cart.find_by("user_id"=> current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart 
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
  <div class="CartContainer">
        <div class="Header">
            <h3 class="Heading">Shopping Cart</h3>
            <h5 class="Action">
              <%= link_to 'Empty cart', @cart, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
            </h5>
        </div>
            <% @cart.line_items.each do |line_item| %>

              <div class="Cart-Items">
                  <div class="about">
                    <h1 class="title"> <%= line_item.article.model.name%>  </h1>
                    <h3 class="subtitle">Nº <%= line_item.article.num%> - <%= line_item.article.color.name%> </h3>
                  </div>
                  <div class="counter">
                    
                    <%= button_to '+', line_items_path(article_id: line_item.article) %>
                    
                    <div class="count"> <%= line_item.quantity%> </div>
                    
                    <% if line_item.quantity!=1 %>
                      <%= button_to '-', decrement_line_item_path(line_item), method: :put %>
                    <% end %>
                  </div>
                  <div class="prices">
                    <div class="amount"> <%= number_to_currency(line_item.total_price) %> </div>
                    <div class="remove"> 
                      <%= link_to 'Delete', line_item_path(line_item),
                      data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
                    </div>
                  </div>
              </div>
            <% end %>

        
      <hr> 
      <div class="checkout">
      <div class="total">
        <div>
          <div class="Subtotal">Sub-Total</div>
          <div class="items"> <%= @cart.totals[:total_items]%> </div>
        </div>
        <div class="total-amount"><%= number_to_currency(@cart.totals[:sum]) %></div>
      </div>
      <%= button_to "Checkout", new_order_path, method: 'get', class: "button" %>
      <%= button_to "Continue shopping", store_index_path, method: 'get' ,  class: "button" %></div>
</div>
    </div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<% if !@cart.line_items.empty? %>
  <%= render @cart %>
<% else %>
  <h2>The cart is empty!</h2>
  <%= button_to "Continue shopping", store_index_path, method: 'get' %>
<% end %>